# -*- coding: utf-8 -*-
"""UpdateStaj2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rfFnn1eKqHKnmROKSJs4m8Oj-TAA6Ywv
"""

!pip install -U spacy
!python -m spacy download en_core_web_sm
!pip install -U spacy-transformers
!pip install -U spacy-lookups-data

import json

TRAIN_DATA = [
    {"text": "Loratadine is used to relieve allergy symptoms such as runny nose and sneezing.", "entities": [(0, 10, "DRUG"), (24, 41, "AllergySymptomRelief")]},
    {"text": "Escitalopram is used to treat depression and generalized anxiety disorder.", "entities": [(0, 11, "DRUG"), (25, 34, "DepressionTreatment"), (39, 66, "AnxietyDisorderTreatment")]},
    {"text": "Hydroxyzine is used to treat anxiety and tension.", "entities": [(0, 10, "DRUG"), (24, 30, "AnxietyTreatment"), (35, 42, "TensionTreatment")]},
    {"text": "Tamsulosin is used to improve urination in men with enlarged prostate.", "entities": [(0, 10, "DRUG"), (38, 58, "EnlargedProstateTreatment")]},
    {"text": "Duloxetine is used to treat depression and anxiety.", "entities": [(0, 9, "DRUG"), (23, 32, "DepressionTreatment"), (37, 44, "AnxietyTreatment")]},
    {"text": "Phenytoin is used to control seizures (convulsions) in certain types of epilepsy.", "entities": [(0, 8, "DRUG"), (22, 36, "SeizureControl")]},
    {"text": "Quetiapine is used to treat schizophrenia and bipolar disorder.", "entities": [(0, 9, "DRUG"), (23, 35, "SchizophreniaTreatment"), (40, 55, "BipolarDisorderTreatment")]},
    {"text": "Mirtazapine is used to treat depression.", "entities": [(0, 10, "DRUG"), (24, 33, "DepressionTreatment")]},
    {"text": "Olanzapine is used to treat schizophrenia and bipolar disorder.", "entities": [(0, 9, "DRUG"), (23, 35, "SchizophreniaTreatment"), (40, 55, "BipolarDisorderTreatment")]},
    {"text": "Fluoxetine is used to treat depression, panic attacks, obsessive-compulsive disorder (OCD), and bulimia nervosa.", "entities": [(0, 10, "DRUG"), (24, 33, "DepressionTreatment"), (38, 50, "PanicAttackTreatment"), (55, 78, "OCDTreatment"), (83, 99, "BulimiaTreatment")]},
    {"text": "Risperidone is used to treat schizophrenia and bipolar disorder.", "entities": [(0, 10, "DRUG"), (24, 36, "SchizophreniaTreatment"), (41, 56, "BipolarDisorderTreatment")]},
    {"text": "Metformin is used to treat type 2 diabetes.", "entities": [(0, 9, "DRUG"), (25, 34, "DiabetesTreatment")]},
    {"text": "Fluticasone is used to relieve seasonal and year-round allergic and non-allergic nasal symptoms.", "entities": [(0, 10, "DRUG"), (24, 41, "AllergySymptomRelief")]},
    {"text": "Guaifenesin is used to relieve chest congestion.", "entities": [(0, 11, "DRUG"), (25, 42, "ChestCongestionRelief")]},
    {"text": "Naproxen is used to treat pain or inflammation caused by conditions such as arthritis, ankylosing spondylitis, tendinitis, bursitis, gout, or menstrual cramps.", "entities": [(0, 8, "DRUG"), (22, 31, "PainTreatment"), (36, 45, "InflammationTreatment"), (101, 116, "ConditionTreatment")]},
    {"text": "Sildenafil is used to treat erectile dysfunction and pulmonary arterial hypertension.", "entities": [(0, 9, "DRUG"), (23, 41, "ErectileDysfunctionTreatment"), (46, 80, "PulmonaryArterialHypertensionTreatment")]},
    {"text": "Trazodone is used to treat depression and insomnia.", "entities": [(0, 9, "DRUG"), (23, 32, "DepressionTreatment"), (37, 45, "InsomniaTreatment")]},
    {"text": "Zolpidem is used to treat insomnia.", "entities": [(0, 7, "DRUG"), (21, 29, "InsomniaTreatment")]},
    {"text": "Atenolol is used to treat angina (chest pain) and hypertension (high blood pressure).", "entities": [(0, 8, "DRUG"), (22, 33, "AnginaTreatment"), (38, 58, "HypertensionTreatment")]},
    {"text": "Citalopram is used to treat depression and panic disorder.", "entities": [(0, 9, "DRUG"), (23, 32, "DepressionTreatment"), (37, 50, "PanicDisorderTreatment")]},
    {"text": "Diphenhydramine is used to relieve allergy symptoms, motion sickness, and insomnia.", "entities": [(0, 14, "DRUG"), (28, 45, "AllergySymptomRelief"), (50, 64, "MotionSicknessRelief"), (69, 77, "InsomniaTreatment")]},
    {"text": "Enalapril is used to treat hypertension (high blood pressure) and heart failure.", "entities": [(0, 8, "DRUG"), (22, 42, "HypertensionTreatment"), (47, 59, "HeartFailureTreatment")]},
    {"text": "Fexofenadine is used to relieve allergy symptoms such as watery eyes, runny nose, itching eyes/nose, sneezing, hives, and itching.", "entities": [(0, 12, "DRUG"), (26, 43, "AllergySymptomRelief")]},
    {"text": "Gabapentin is used to treat seizures and neuropathic pain.", "entities": [(0, 9, "DRUG"), (23, 30, "SeizureTreatment"), (35, 50, "NeuropathicPainTreatment")]},
    {"text": "Hydrocodone is used to relieve severe pain.", "entities": [(0, 11, "DRUG"), (25, 35, "SeverePainRelief")]},
    {"text": "Ipratropium is used to treat bronchospasm.", "entities": [(0, 10, "DRUG"), (24, 37, "BronchospasmTreatment")]},
    {"text": "Ketorolac is used to relieve moderately severe pain.", "entities": [(0, 9, "DRUG"), (23, 45, "ModeratelySeverePainRelief")]},
    {"text": "Loperamide is used to control diarrhea.", "entities": [(0, 10, "DRUG"), (24, 36, "DiarrheaControl")]},
    {"text": "Mometasone is used to treat inflammation and allergy symptoms.", "entities": [(0, 9, "DRUG"), (23, 34, "InflammationTreatment"), (39, 56, "AllergySymptomRelief")]},
    {"text": "Nystatin is used to treat fungal infections.", "entities": [(0, 8, "DRUG"), (22, 38, "FungalInfectionTreatment")]},
    {"text": "Olanzapine is used to treat schizophrenia and bipolar disorder.", "entities": [(0, 9, "DRUG"), (23, 35, "SchizophreniaTreatment"), (40, 55, "BipolarDisorderTreatment")]},
    {"text": "Pantoprazole is used to reduce stomach acid and treat GERD.", "entities": [(0, 12, "DRUG"), (26, 40, "AcidReducer"), (45, 49, "GERDTreatment")]},
    {"text": "Quinapril is used to treat hypertension and congestive heart failure.", "entities": [(0, 9, "DRUG"), (23, 34, "HypertensionTreatment"), (39, 61, "HeartFailureTreatment")]},
    {"text": "Ropinirole is used to treat Parkinson's disease and restless legs syndrome.", "entities": [(0, 9, "DRUG"), (23, 38, "ParkinsonsDiseaseTreatment"), (43, 62, "RestlessLegsSyndromeTreatment")]},
    {"text": "Salmeterol is used to prevent asthma attacks.", "entities": [(0, 10, "DRUG"), (24, 39, "AsthmaAttackPrevention")]},
    {"text": "Tacrolimus is used to prevent organ rejection after a kidney, liver, or heart transplant.", "entities": [(0, 10, "DRUG"), (24, 41, "OrganRejectionPrevention"), (46, 73, "TransplantTreatment")]},
    {"text": "Ursodiol is used to dissolve gallstones in patients who do not want surgery or cannot have surgery.", "entities": [(0, 8, "DRUG"), (22, 38, "GallstoneDissolution")]},
    {"text": "Valsartan is used to treat hypertension and heart failure.", "entities": [(0, 9, "DRUG"), (23, 34, "HypertensionTreatment"), (39, 51, "HeartFailureTreatment")]},
    {"text": "Zaleplon is used to treat insomnia (difficulty falling asleep).", "entities": [(0, 8, "DRUG"), (22, 30, "InsomniaTreatment")]},
    {"text": "Allopurinol is used to reduce uric acid in the body.", "entities": [(0, 11, "DRUG"), (25, 41, "UricAcidReduction")]},
    {"text": "Bisoprolol is used to treat hypertension and heart failure.", "entities": [(0, 10, "DRUG"), (24, 35, "HypertensionTreatment"), (40, 52, "HeartFailureTreatment")]},
    {"text": "Ceftriaxone is an antibiotic used to treat bacterial infections.", "entities": [(0, 11, "DRUG"), (27, 36, "Antibiotic"), (45, 63, "InfectionsTreatment")]},
    {"text": "Dexamphetamine is used to treat attention deficit hyperactivity disorder (ADHD).", "entities": [(0, 14, "DRUG"), (28, 57, "ADHDTreatment")]},
    {"text": "Ezetimibe is used to lower cholesterol levels.", "entities": [(0, 9, "DRUG"), (23, 38, "CholesterolLowering")]},
    {"text": "Fentanyl is used to treat severe pain, such as in cancer patients.", "entities": [(0, 8, "DRUG"), (22, 31, "SeverePainTreatment"), (37, 53, "CancerPainTreatment")]},
    {"text": "Glyburide is used to treat type 2 diabetes.", "entities": [(0, 9, "DRUG"), (23, 32, "DiabetesTreatment")]},
    {"text": "Haloperidol is used to treat schizophrenia and acute psychosis.", "entities": [(0, 11, "DRUG"), (25, 37, "SchizophreniaTreatment"), (42, 56, "AcutePsychosisTreatment")]},
    {"text": "Imipramine is used to treat depression and bedwetting in children.", "entities": [(0, 10, "DRUG"), (24, 33, "DepressionTreatment"), (38, 58, "BedwettingTreatment")]},
    {"text": "Juniper oil is used in aromatherapy and skin conditions.", "entities": [(0, 11, "DRUG"), (26, 37, "AromatherapyUse"), (42, 56, "SkinConditionTreatment")]},
    {"text": "Ketoconazole is used to treat fungal infections.", "entities": [(0, 12, "DRUG"), (26, 42, "FungalInfectionTreatment")]},
    {"text": "Lactulose is used to treat constipation.", "entities": [(0, 9, "DRUG"), (23, 34, "ConstipationTreatment")]},
    {"text": "Melatonin is used to treat sleep disorders such as insomnia and jet lag.", "entities": [(0, 9, "DRUG"), (23, 35, "InsomniaTreatment"), (40, 47, "JetLagTreatment")]},
    {"text": "Nitroglycerin is used to relieve chest pain (angina).", "entities": [(0, 13, "DRUG"), (27, 37, "AnginaPainRelief")]},
    {"text": "Ondansetron is used to prevent nausea and vomiting caused by chemotherapy and radiation therapy.", "entities": [(0, 10, "DRUG"), (24, 31, "NauseaPrevention"), (36, 54, "VomitingPrevention"), (70, 87, "ChemotherapyTreatment"), (92, 110, "RadiationTherapyTreatment")]},
    {"text": "Paroxetine is used to treat depression, anxiety disorders, and post-traumatic stress disorder (PTSD).", "entities": [(0, 10, "DRUG"), (24, 33, "DepressionTreatment"), (38, 53, "AnxietyDisorderTreatment"), (58, 92, "PTSDTreatment")]},
    {"text": "Quinine is used to treat malaria.", "entities": [(0, 7, "DRUG"), (21, 28, "MalariaTreatment")]},
    {"text": "Ranitidine is used to reduce stomach acid and treat ulcers and acid reflux.", "entities": [(0, 9, "DRUG"), (23, 37, "AcidReducer"), (42, 47, "UlcerTreatment"), (52, 63, "GERDTreatment")]},
    {"text": "Sotalol is used to treat certain types of irregular heartbeat (arrhythmias).", "entities": [(0, 7, "DRUG"), (21, 52, "IrregularHeartbeatTreatment")]},
    {"text": "Tiotropium is used to treat chronic obstructive pulmonary disease (COPD).", "entities": [(0, 9, "DRUG"), (23, 59, "COPDTreatment")]},
    {"text": "Urea cream is used to treat dry/rough skin conditions (e.g., eczema, psoriasis, corns, callus) and some nail problems (e.g., ingrown nails).", "entities": [(0, 10, "DRUG"), (24, 72, "SkinConditionTreatment"), (77, 101, "NailProblemTreatment")]},
    {"text": "Valproic acid is used to treat epilepsy, bipolar disorder, and migraine headaches.", "entities": [(0, 13, "DRUG"), (27, 35, "EpilepsyTreatment"), (40, 55, "BipolarDisorderTreatment"), (60, 77, "MigraineHeadacheTreatment")]},
    {"text": "Warfarin is used to prevent blood clots from forming or growing larger in your blood and blood vessels.", "entities": [(0, 8, "DRUG"), (22, 41, "BloodClotPrevention")]},
    {"text": "Xylometazoline is used to relieve nasal discomfort caused by colds, allergies, and hay fever.", "entities": [(0, 14, "DRUG"), (28, 44, "NasalDiscomfortRelief")]},
    {"text": "Yohimbine is used to treat male sexual function problems (impotence or erectile dysfunction-ED).", "entities": [(0, 9, "DRUG"), (23, 58, "SexualFunctionProblemTreatment")]},
    {"text": "Zinc oxide is used to treat diaper rash, minor burns, severely chapped skin, or other minor skin irritations.", "entities": [(0, 10, "DRUG"), (24, 42, "DiaperRashTreatment"), (47, 59, "MinorBurnsTreatment"), (64, 90, "SkinIrritationTreatment")]},
]

with open('data.json', 'w') as f:
    json.dump(TRAIN_DATA, f)

import spacy
from spacy.training.example import Example
import random

# Veri setinizi yükleyin
with open('data.json', 'r') as f:
    TRAIN_DATA = json.load(f)

# Varsayılan İngilizce modelini yükleyin
nlp = spacy.load("en_core_web_sm")

# Modeldeki entity recognizer bileşenini alın
ner = nlp.get_pipe("ner")

# Yeni etiketler ekleyin
for entry in TRAIN_DATA:
    for ent in entry.get("entities"):
        ner.add_label(ent[2])

# Lookups data yükleyin
import spacy.lookups
lookups = spacy.lookups.load_lookups("en", ["lexeme_norm"])

# Diğer bileşenlerin geçici olarak devre dışı bırakılması
unaffected_pipes = [pipe for pipe in nlp.pipe_names if pipe != "ner"]

# Modeli eğitme
with nlp.disable_pipes(*unaffected_pipes):
    optimizer = nlp.begin_training()
    for i in range(20):
        random.shuffle(TRAIN_DATA)
        losses = {}
        for entry in TRAIN_DATA:
            doc = nlp.make_doc(entry["text"])
            example = Example.from_dict(doc, {"entities": entry["entities"]})
            nlp.update([example], losses=losses, drop=0.5, sgd=optimizer)
        print(losses)

# Eğitilen modeli kaydetme
nlp.to_disk("custom_model")

# Eğitilen modeli yükleme
nlp_custom = spacy.load("custom_model")

# Modeli test etme
text = """
Metformin is commonly used to treat type 2 diabetes.
Loratadine, on the other hand, helps relieve allergy symptoms such as runny nose and sneezing.
Ibuprofen is an anti-inflammatory used to reduce pain and inflammation.
Zolpidem is prescribed for treating insomnia, while Fluoxetine is effective in managing depression and panic attacks.
"""

doc = nlp_custom(text)

# Tanımlanan varlıkları yazdırın
for ent in doc.ents:
    print(ent.text, "|", ent.label_)

from spacy import displacy
displacy.render(doc, style="ent")